USE [master]
GO
/****** Object:  Database [EFExampleBug] ******/
CREATE DATABASE [EFExampleBug]
GO
ALTER DATABASE [EFExampleBug] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EFExampleBug].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [EFExampleBug] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [EFExampleBug] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [EFExampleBug] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [EFExampleBug] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [EFExampleBug] SET ARITHABORT OFF 
GO
ALTER DATABASE [EFExampleBug] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [EFExampleBug] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [EFExampleBug] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [EFExampleBug] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [EFExampleBug] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [EFExampleBug] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [EFExampleBug] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [EFExampleBug] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [EFExampleBug] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [EFExampleBug] SET  DISABLE_BROKER 
GO
ALTER DATABASE [EFExampleBug] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [EFExampleBug] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [EFExampleBug] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [EFExampleBug] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [EFExampleBug] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [EFExampleBug] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [EFExampleBug] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [EFExampleBug] SET RECOVERY FULL 
GO
ALTER DATABASE [EFExampleBug] SET  MULTI_USER 
GO
ALTER DATABASE [EFExampleBug] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [EFExampleBug] SET DB_CHAINING OFF 
GO
ALTER DATABASE [EFExampleBug] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [EFExampleBug] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [EFExampleBug] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'EFExampleBug', N'ON'
GO
ALTER DATABASE [EFExampleBug] SET QUERY_STORE = OFF
GO
USE [EFExampleBug]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
USE [EFExampleBug]
GO
/****** Object:  Table [dbo].[Blog] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Blog](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Blog] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Comment] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Comment](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Text] [nvarchar](50) NOT NULL,
	[PostId] [int] NOT NULL,
 CONSTRAINT [PK_Comment] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Post] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Post](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Title] [nvarchar](50) NOT NULL,
	[BlogId] [int] NOT NULL,
 CONSTRAINT [PK_Post] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Comment]  WITH CHECK ADD  CONSTRAINT [FK_Comment_Post] FOREIGN KEY([PostId])
REFERENCES [dbo].[Post] ([Id])
GO
ALTER TABLE [dbo].[Comment] CHECK CONSTRAINT [FK_Comment_Post]
GO
ALTER TABLE [dbo].[Post]  WITH CHECK ADD  CONSTRAINT [FK_Post_Blog] FOREIGN KEY([BlogId])
REFERENCES [dbo].[Blog] ([Id])
GO
ALTER TABLE [dbo].[Post] CHECK CONSTRAINT [FK_Post_Blog]
GO
USE [master]
GO
ALTER DATABASE [EFExampleBug] SET  READ_WRITE 
GO

